remote_theme: carlosperate/jekyll-theme-rtd
title: JP Docs
description: Documentation for most of my projects. (originally called JP Wiki)
repo_url: 'https://github.com/mobilex1122/docs'
github_docs_folder: false